/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/consumer/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia cadastro de consumidor */
        post: operations["registerConsumer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/consumer/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma cadastro do consumidor com OTP */
        post: operations["confirmConsumerRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia cadastro empresarial */
        post: operations["registerCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma OTP e inicia enrolamento TOTP da empresa
         * @description Resposta one-shot com token temporário de escopo `totp_pending` e material de enrolamento 2FA.
         *     Não logar nem exemplificar `totpSecret`, `qrCodeDataUrl` ou `recoveryCodes` com valores reais.
         */
        post: operations["confirmCompanyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reivindica perfil empresarial por CNPJ */
        post: operations["claimCompanyProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/company/claim/{claimId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta status da reivindicação empresarial */
        get: operations["getCompanyClaimStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login ou cadastro via token Google */
        post: operations["ssoGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login ou cadastro via token Apple */
        post: operations["ssoApple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre novo caso */
        post: operations["openCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta caso por UUID interno ou publicId */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta trilha auditável do caso e aceite legal */
        get: operations["getCaseAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ENVIADO -> EM_MODERACAO */
        post: operations["startModeration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EM_MODERACAO -> PUBLICADO */
        post: operations["approveModeration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/moderation/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EM_MODERACAO -> NAO_RESOLVIDO */
        post: operations["rejectModeration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/notify-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PUBLICADO -> AGUARDANDO_RESPOSTA_EMPRESA
         * @description Endpoint interno protegido por assinatura HMAC no header `X-Internal-Signature`.
         */
        post: operations["notifyCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/company/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AGUARDANDO_RESPOSTA_EMPRESA -> EM_NEGOCIACAO */
        post: operations["companyRespond"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EM_NEGOCIACAO -> RESOLVIDO
         * @description Exige confirmação de consumidor e empresa.
         */
        post: operations["resolveCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/close-unresolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EM_NEGOCIACAO ou AGUARDANDO_RESPOSTA_EMPRESA -> NAO_RESOLVIDO */
        post: operations["closeUnresolvedCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterConsumerRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
            phone?: string;
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        RegisterCompanyRequest: {
            /** Format: email */
            email: string;
            password: string;
            cnpj: string;
            legalName: string;
            tradeName?: string;
            fullName: string;
            phone?: string;
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        RegisterConfirmRequest: {
            registrationToken: string;
            otp: string;
        };
        ClaimCompanyRequest: {
            cnpj: string;
            legalName: string;
            tradeName?: string;
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
            phone?: string;
            documents: components["schemas"]["ClaimDocument"][];
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        ClaimDocument: {
            /** Format: uri */
            url: string;
            fileName: string;
            mimeType: string;
            sizeBytes: number;
        };
        SsoAuthRequest: {
            idToken: string;
            lgpdAccepted: boolean;
            lgpdVersion: string;
        };
        RegisterInitResponse: {
            /** Format: uuid */
            userId?: string;
            /** @description Token temporário. Não logar nem exemplificar com valor real. */
            registrationToken?: string;
        };
        ClaimCreatedResponse: {
            /** Format: uuid */
            claimId?: string;
            /** @description Token temporário. Não logar nem exemplificar com valor real. */
            registrationToken?: string;
        };
        ClaimStatusResponse: {
            /** Format: uuid */
            claimId?: string;
            /** @enum {string} */
            status?: "pending_review" | "approved" | "rejected";
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            reviewedAt?: string | null;
            rejectionReason?: string | null;
        };
        TokensResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        /** @description Resposta one-shot para configuração obrigatória de 2FA empresarial. */
        CompanyConfirmResponse: {
            /** @description Token temporário com escopo `totp_pending`. */
            accessToken?: string;
            /** @description Segredo TOTP one-shot. Não logar nem exemplificar. */
            totpSecret?: string;
            /** @description QR Code TOTP em data URL. Conteúdo sensível one-shot. */
            qrCodeDataUrl?: string;
            /** @description Códigos de recuperação one-shot. Não logar nem exemplificar. */
            recoveryCodes?: string[];
        };
        OpenCaseRequest: {
            /** Format: uuid */
            companyId: string;
            /** @enum {string} */
            experienceType: "reclamacao" | "denuncia" | "elogio" | "duvida_resolvida";
            /** @enum {string} */
            category: "imoveis" | "servicos" | "ecommerce" | "financeiro" | "saude" | "educacao" | "outro";
            description: string;
            monetaryValue?: number | null;
            /** Format: date */
            occurredAt: string;
            questionnaireAnswers?: {
                [key: string]: unknown;
            };
            legalAcceptance: {
                termId: string;
                contentHashEcho: string;
            };
        };
        CaseCreatedResponse: {
            /** Format: uuid */
            id?: string;
            publicId?: string;
            status?: components["schemas"]["CaseStatus"];
        };
        CaseResponse: {
            /** Format: uuid */
            id?: string;
            publicId?: string;
            status?: components["schemas"]["CaseStatus"];
            experienceType?: string;
            category?: string;
            description?: string;
            monetaryValue?: number | null;
            /** Format: date */
            occurredAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            publishedAt?: string | null;
        };
        CaseAuditResponse: {
            case?: {
                /** Format: uuid */
                id?: string;
                status?: components["schemas"]["CaseStatus"];
            };
            termAcceptance?: {
                termVersion?: string;
                contentHash?: string;
                /** Format: date-time */
                acceptedAt?: string;
                ip?: string;
            } | null;
        };
        ResolveCaseRequest: {
            consumerConfirmed: boolean;
            companyConfirmed: boolean;
        };
        RejectCaseRequest: {
            reason: string;
        };
        CloseUnresolvedRequest: {
            reason: string;
        };
        TransitionResponse: {
            /** Format: uuid */
            caseId?: string;
            fromStatus?: components["schemas"]["CaseStatus"];
            toStatus?: components["schemas"]["CaseStatus"];
            /** Format: uuid */
            transitionId?: string;
        };
        /** @enum {string} */
        CaseStatus: "ENVIADO" | "EM_MODERACAO" | "PUBLICADO" | "AGUARDANDO_RESPOSTA_EMPRESA" | "EM_NEGOCIACAO" | "RESOLVIDO" | "NAO_RESOLVIDO";
        ErrorResponse: {
            statusCode?: number;
            message?: unknown;
            error?: string;
            code?: string;
        };
    };
    responses: {
        /** @description Requisição inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Não autenticado ou token inválido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Sem permissão */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflito de regra de negócio ou transição inválida */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validação semântica inválida */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Transição executada com timeline/auditoria */
        TransitionOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TransitionResponse"];
            };
        };
    };
    parameters: {
        /** @description UUID interno do caso ou publicId operacional. */
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConsumerRequest"];
            };
        };
        responses: {
            /** @description Cadastro iniciado e OTP enviado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterInitResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    confirmConsumerRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConfirmRequest"];
            };
        };
        responses: {
            /** @description Conta ativada e tokens emitidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    registerCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterCompanyRequest"];
            };
        };
        responses: {
            /** @description Cadastro iniciado e OTP enviado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterInitResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    confirmCompanyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConfirmRequest"];
            };
        };
        responses: {
            /** @description OTP válido e enrolamento TOTP iniciado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyConfirmResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    claimCompanyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCompanyRequest"];
            };
        };
        responses: {
            /** @description Claim registrado para análise e OTP enviado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimCreatedResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCompanyClaimStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claimId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status atual do claim retornado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    ssoGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoAuthRequest"];
            };
        };
        responses: {
            /** @description Autenticado via Google e tokens emitidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    ssoApple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoAuthRequest"];
            };
        };
        responses: {
            /** @description Autenticado via Apple e tokens emitidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    openCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenCaseRequest"];
            };
        };
        responses: {
            /** @description Caso criado com publicId gerado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreatedResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados públicos/minimizados do caso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCaseAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auditoria autorizada do caso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAuditResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startModeration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    approveModeration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectModeration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectCaseRequest"];
            };
        };
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    notifyCompany: {
        parameters: {
            query?: never;
            header: {
                /** @description Assinatura HMAC-SHA256 do body com segredo interno. */
                "X-Internal-Signature": string;
            };
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TransitionOk"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    companyRespond: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveCaseRequest"];
            };
        };
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    closeUnresolvedCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID interno do caso ou publicId operacional. */
                id: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseUnresolvedRequest"];
            };
        };
        responses: {
            200: components["responses"]["TransitionOk"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
